# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_date', models.DateTimeField(auto_now_add=True, verbose_name='签到日期')),
            ],
            options={
                'verbose_name': '签到表',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='用户姓名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户表',
            },
        ),
        migrations.AddField(
            model_name='sign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdemo.UserInfo', verbose_name='用户'),
        ),
    ]
